# Site settings
title: XIN MING
email: xinerd@fmachine.cn
description: > # this means to ignore newlines until "baseurl:"
  Hello World.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fmachine.cn" # the base hostname & protocol for your site
twitter_username: xinerd
github_username:  xinerd

# Build settings
markdown: kramdown
